# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('goodreads_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ratings_count', models.IntegerField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['average_rating'],
            },
        ),
    ]
