# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160102_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
