# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_contestant',
            field=models.BooleanField(default=False),
        ),
    ]
