# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('book', 'user')]),
        ),
    ]
