# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20160102_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklybook',
            name='week_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(53), django.core.validators.MinValueValidator(1)]),
        ),
    ]
