# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_groups', '0002_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgroup',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set([('book_group', 'user')]),
        ),
    ]
