# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_groups', '0003_auto_20151231_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookgroup',
            name='owner',
        ),
    ]
